### PR TITLE
#161049231 Create a login page

### PR DESCRIPTION
**Pull request by kathy254**
**What does this PR do?**
It creates a login page for the admin and the store attendant.

**Description of the tasks completed**

1. Created a feature branch and a UI directory
2. Added HTML for a login page
3. Added CSS for the login page
4. Added two images

**How can you test this?**
Clone this repository to your local machine and run the login.html file to view the user interface

**What are the relevant pivotal tracker stories**
#161049231

### CODE REVIEW

**Comment by kathy254** [comment]
screenshot from 2018-10-08 20-39-05

**Comment by dev-jey** [comment]
Looks good

**Comment by sharkdevs** [comment]
beautiful...

**Comment by kwanj-k** [comment]
One more thing
thats not the way to name a PR
refer here https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices

**Comment by kwanj-k** [comment]
nice

**Comment by eduhmik** [comment]
Simple and stylish design
You may also consider adding a recover password link

**Comment by kathy254** [comment]
> Simple and stylish design
> You may also consider adding a recover password link

Thanks.
screenshot from 2018-10-09 06-12-20

**Comment by kamaudan** [comment]
Good work, I like the colors an positioning, maybe you can make the form occupy more space, because is the main thing on the page.

**Comment by Paulvitalis200** [comment]
This is very good.

**Pull request merged**
